config/routes.rb
require 'sidekiq'
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, path_names: {sign_in: "login", sign_out: "logout"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get '/connections' => 'home#connections'
  get '/keywords' => 'home#keywords'
  get '/all_keywords' => 'home#all_keywords'
  get '/visuals' => 'home#visuals'

  post '/ingestion/youtube' => 'worker_processor#youtube'

  post '/ingestion/reddit' => 'worker_processor#reddit'

  post '/ingestion/bing' => 'worker_processor#bing'

  post '/ingestion/wiki' => 'worker_processor#wiki'

  post '/ingestion/giphy' => 'worker_processor#giphy'


  mount Sidekiq::Web => '/sidekiq'
end

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/keywords">What's New</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<% if user_signed_in? %>
	      <ul class="nav navbar-nav">
	        <li><%= link_to 'Connections', connections_path %></li>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
        
					<li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%=current_user.email%> <span class="caret"></span></a>
          	<ul class="dropdown-menu" role="menu">
						
	            <li><%= link_to 'Edit profile', edit_user_registration_path %></a></li>
	            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
						</ul>
        	</li>
	      </ul>
			<% else %>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Sign up', new_user_registration_path %></li>
				<li><%= link_to 'Login', new_user_session_path %></li>
			</ul>
			<% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>